#include <cgreen/cgreen.h>
#include <core/fdt.h>
#include <stdlib.h>

Describe (FDT);
BeforeEach (FDT)
{
}
AfterEach (FDT)
{
}

const char *qemu_dtb_filename = "data/qemu_virt.dtb";
const char *test_dtb_0 = "data/test_00.dtb";
const char *test_dtb_1 = "data/test_01.dtb";

struct fdt_header *get_dtb_base (const char *filename);

Ensure (FDT, get_address)
{
	void *fdt = get_dtb_base (qemu_dtb_filename);
	assert_that (fdt != NULL);
}

struct fdt *fdt_setup_struct (struct fdt_header *);
Ensure (FDT, setup_struct)
{
	struct fdt *fdt = fdt_setup_struct (
		(struct fdt_header *)get_dtb_base (qemu_dtb_filename));
	assert_that (fdt != NULL);
}

struct fdt *fdt_parse (struct fdt_header *);
Ensure (FDT, fdt_parse)
{
	struct fdt *fdt = fdt_parse (
		(struct fdt_header *)get_dtb_base (qemu_dtb_filename));
	assert_that (fdt != NULL);
}

/* generated by `$fdtdump data/qemu_virt.dtb`
/dts-v1/;
// magic:               0xd00dfeed
// totalsize:           0x4f1 (1265)
// off_dt_struct:       0x38
// off_dt_strings:      0x408
// off_mem_rsvmap:      0x28
// version:             17
// last_comp_version:   16
// boot_cpuid_phys:     0x0
// size_dt_strings:     0xe9
// size_dt_struct:      0x3d0
...
*/

uint32_t fdt_calc_structblock_totalsize (struct fdt_node *);
Ensure (FDT, structblock_size_all)
{
	struct fdt *fdt = fdt_parse (
		(struct fdt_header *)get_dtb_base (qemu_dtb_filename));
	assert_that (fdt != NULL);
	assert_that (NULL != fdt->root_node);

	int size = fdt_calc_structblock_totalsize (fdt->root_node);
	// 	printf ("totalsize 0x%x\n", size);
	assert_that (size == 0x3d0);
}

struct string_list {
	struct string_list *next;
	char *str;
	u32 offset;
};
uint32_t fdt_calc_stringblock_totalsize (struct fdt_node *node,
					 struct string_list **);
Ensure (FDT, stringblock_size_all)
{
	struct fdt *fdt = fdt_parse (
		(struct fdt_header *)get_dtb_base (qemu_dtb_filename));
	assert_that (fdt != NULL);
	assert_that (NULL != fdt->root_node);

	struct string_list *str_list;
	int size = fdt_calc_stringblock_totalsize (fdt->root_node, &str_list);
	// 	printf ("totalsize 0x%x\n", size);
	assert_that (size == 0xe9);
	for (struct string_list *c = str_list; c; c = c->next) {
		printf ("%s: %s 0x%x\n", __func__, c->str, c->offset);
	}
}

/*
$ fdtdump test_00.dtb

**** fdtdump is a low-level debugging tool, not meant for general use.
**** If you want to decompile a dtb, you probably want
****     dtc -I dtb -O dts <filename>

/dts-v1/;
// magic:               0xd00dfeed
// totalsize:           0x48 (72)
// off_dt_struct:       0x38
// off_dt_strings:      0x48
// off_mem_rsvmap:      0x28
// version:             17
// last_comp_version:   16
// boot_cpuid_phys:     0x0
// size_dt_strings:     0x0
// size_dt_struct:      0x10

/ {
};
 */
Ensure (FDT, structblock_size_0)
{
	struct fdt *fdt =
		fdt_parse ((struct fdt_header *)get_dtb_base (test_dtb_0));
	assert_that (fdt != NULL);
	assert_that (NULL != fdt->root_node);

	int size = fdt_calc_structblock_totalsize (fdt->root_node);
	// 	printf ("totalsize 0x%x\n", size);
	assert_that (size == 0x10);
}
/*
$ fdtdump test_01.dtb

**** fdtdump is a low-level debugging tool, not meant for general use.
**** If you want to decompile a dtb, you probably want
****     dtc -I dtb -O dts <filename>

/dts-v1/;
// magic:               0xd00dfeed
// totalsize:           0xcf (207)
// off_dt_struct:       0x38
// off_dt_strings:      0x98
// off_mem_rsvmap:      0x28
// version:             17
// last_comp_version:   16
// boot_cpuid_phys:     0x0
// size_dt_strings:     0x37
// size_dt_struct:      0x60

/ {
    interrupt-parent = <0x00008001>;
    #size-cells = <0x00000002>;
    #address-cells = <0x00000002>;
    compatible = "linux,dummy-virt";
};
 */
Ensure (FDT, structblock_size_1)
{
	struct fdt *fdt =
		fdt_parse ((struct fdt_header *)get_dtb_base (test_dtb_1));
	assert_that (fdt != NULL);
	assert_that (NULL != fdt->root_node);

	int size = fdt_calc_structblock_totalsize (fdt->root_node);
	assert_that (size == 0x60);
}

Ensure (FDT, stringblock_size_1)
{
	struct fdt *fdt =
		fdt_parse ((struct fdt_header *)get_dtb_base (test_dtb_1));

	struct string_list *str_list = NULL;
	fdt_calc_stringblock_totalsize (fdt->root_node, &str_list);
	for (struct string_list *c = str_list; c; c = c->next) {
		printf ("%s: %s 0x%x\n", __func__, c->str, c->offset);
	}
}

uint32_t swap_u32 (uint32_t);

void fdt_load_to (struct fdt *, void **);
Ensure (FDT, fdt_load_0)
{
	struct fdt_header *header =
		(struct fdt_header *)get_dtb_base (test_dtb_0);
	struct fdt *fdt = fdt_parse (header);

	void *base = calloc (2, swap_u32 (header->totalsize));

	fdt_load_to (fdt, base);

	struct fdt_header *nheader = (struct fdt_header *)base;

#define FDT_MAGIC_BIG 0xedfe0dd0
	assert_that (nheader->magic, is_equal_to (FDT_MAGIC_BIG));

	assert_that (swap_u32 (nheader->off_dt_struct),
		     is_equal_to (swap_u32 (header->off_dt_struct)));
	assert_that (swap_u32 (nheader->off_dt_strings),
		     is_equal_to (swap_u32 (header->off_dt_strings)));
	assert_that (swap_u32 (nheader->size_dt_struct),
		     is_equal_to (swap_u32 (header->size_dt_struct)));
	assert_that (swap_u32 (nheader->size_dt_strings),
		     is_equal_to (swap_u32 (header->size_dt_strings)));

	assert_that (swap_u32 (nheader->totalsize),
		     is_equal_to (swap_u32 (header->totalsize)));
}

Ensure (FDT, fdt_load_1)
{
	struct fdt_header *header =
		(struct fdt_header *)get_dtb_base (qemu_dtb_filename);
	struct fdt *fdt = fdt_parse (header);

	void *base = calloc (2, swap_u32 (header->totalsize));

	fdt_load_to (fdt, base);

	struct fdt_header *nheader = (struct fdt_header *)base;
	assert_that (swap_u32 (nheader->off_dt_struct),
		     is_equal_to (swap_u32 (header->off_dt_struct)));
	assert_that (swap_u32 (nheader->off_dt_strings),
		     is_equal_to (swap_u32 (header->off_dt_strings)));
	assert_that (swap_u32 (nheader->size_dt_struct),
		     is_equal_to (swap_u32 (header->size_dt_struct)));
	assert_that (swap_u32 (nheader->size_dt_strings),
		     is_equal_to (swap_u32 (header->size_dt_strings)));

	assert_that (swap_u32 (nheader->totalsize),
		     is_equal_to (swap_u32 (header->totalsize)));
}

int
main (int argc, char **argv)
{
	TestSuite *suite = create_test_suite ();
	add_test_with_context (suite, FDT, get_address);
	add_test_with_context (suite, FDT, setup_struct);

	add_test_with_context (suite, FDT, structblock_size_0);
	add_test_with_context (suite, FDT, structblock_size_1);
	add_test_with_context (suite, FDT, structblock_size_all);

	add_test_with_context (suite, FDT, stringblock_size_1);
	add_test_with_context (suite, FDT, stringblock_size_all);

	add_test_with_context (suite, FDT, fdt_load_0);
	add_test_with_context (suite, FDT, fdt_load_1);

	return run_test_suite (suite, create_text_reporter ());
}
