
// Translation Control Register
#define TCR_T0SZ_OFFSET (0)
// The region size is 2 ** (64 - T0SZ) bytes.
#define TCR_T0SZ        (16 << TCR_T0SZ_OFFSET)

#define TCR_T1SZ_OFFSET (16)
#define TCR_T1SZ        (16 << TCR_T0SZ_OFFSET)

#define TCR_SH0_OFFSET  (12)
#define TCR_SH0_NON_SHARE   (0b00U << TCR_SH0_OFFSET)
#define TCR_SH0_OUT_SHARE   (0b10U << TCR_SH0_OFFSET)
#define TCR_SH0_INN_SHARE   (0b11U << TCR_SH0_OFFSET)
#define TCR_SH1_OFFSET  (28)
#define TCR_SH1_NON_SHARE   (0b00U << TCR_SH1_OFFSET)
#define TCR_SH1_OUT_SHARE   (0b10U << TCR_SH1_OFFSET)
#define TCR_SH1_INN_SHARE   (0b11U << TCR_SH1_OFFSET)

#define TCR_ORGN0_OFFSET    (10)
#define TCR_ORGN0_NON_CACHE (0b00U << TCR_ORGN0_OFFSET)
#define TCR_ORGN0_WB_RA_RA  (0b01U << TCR_ORGN0_OFFSET)
#define TCR_ORGN0_WT_RA_NRA (0b10U << TCR_ORGN0_OFFSET)
#define TCR_ORGN0_WB_RA_NWA (0b11U << TCR_ORGN0_OFFSET)

#define TCR_ORGN1_OFFSET    (26)
#define TCR_ORGN1_NON_CACHE (0b00U << TCR_ORGN1_OFFSET)
#define TCR_ORGN1_WB_RA_RA  (0b01U << TCR_ORGN1_OFFSET)
#define TCR_ORGN1_WT_RA_NRA (0b10U << TCR_ORGN1_OFFSET)
#define TCR_ORGN1_WB_RA_NWA (0b11U << TCR_ORGN1_OFFSET)

#define TCR_TG0_OFFSET  (14)
#define TCR_TG0_4K      (0b00U << TCR_TG0_OFFSET)
#define TCR_TG0_16K     (0b10U << TCR_TG0_OFFSET)
#define TCR_TG0_64K     (0b01U << TCR_TG0_OFFSET)

#define TCR_TG1_OFFSET  (30)
#define TCR_TG1_4K      (0b10U << TCR_TG1_OFFSET)
#define TCR_TG1_16K     (0b01U << TCR_TG1_OFFSET)
#define TCR_TG1_64K     (0b11U << TCR_TG1_OFFSET)

#define TCR_IPS_OFFSET  (32)
#define TCR_IPS_32  (0b000ULL << TCR_IPS_OFFSET)
#define TCR_IPS_36  (0b001ULL << TCR_IPS_OFFSET)
#define TCR_IPS_40  (0b010ULL << TCR_IPS_OFFSET)
#define TCR_IPS_42  (0b011ULL << TCR_IPS_OFFSET)
#define TCR_IPS_44  (0b100ULL << TCR_IPS_OFFSET)
#define TCR_IPS_48  (0b101ULL << TCR_IPS_OFFSET)
#define TCR_IPS_52  (0b110ULL << TCR_IPS_OFFSET)

#define TCR_IRGN0_OFFSET    (8)
#define TCR_IRGN0_NON_CACHE (0b00U << TCR_IRGN0_OFFSET)
#define TCR_IRGN0_RB_RA_WA  (0b01U << TCR_IRGN0_OFFSET)
#define TCR_IRGN0_WT_RA_NWA (0b10U << TCR_IRGN0_OFFSET)
#define TCR_IRGN0_WB_RA_NWA (0b11U << TCR_IRGN0_OFFSET)

#define TCR_IRGN1_OFFSET    (24)
#define TCR_IRGN1_NON_CACHE (0b00U << TCR_IRGN1_OFFSET)
#define TCR_IRGN1_RB_RA_WA  (0b01U << TCR_IRGN1_OFFSET)
#define TCR_IRGN1_WT_RA_NWA (0b10U << TCR_IRGN1_OFFSET)
#define TCR_IRGN1_WB_RA_NWA (0b11U << TCR_IRGN1_OFFSET)

#define TCR_VALUE   (\
        TCR_T0SZ | TCR_TG0_4K | TCR_SH0_INN_SHARE | TCR_ORGN0_WB_RA_RA | TCR_IRGN0_RB_RA_WA |\
        TCR_T1SZ | TCR_TG1_4K | TCR_SH1_INN_SHARE | TCR_ORGN1_WB_RA_RA | TCR_IRGN1_RB_RA_WA |\
        TCR_IPS_32)

