
bits-n = 32
bits-y = 64
CFLAGS = -m$(bits-$(CONFIG_64)) -mno-red-zone -mno-sse -nostdinc -g -O \
-ffreestanding -fno-builtin -fno-stack-protector $(backtrace) -fno-PIE \
-fno-strict-aliasing -Wall -Wno-address-of-packed-member $(CONSTANTS-y) \
-I$(DIR) -Iinclude
ASFLAGS = -m$(bits-$(CONFIG_64)) -g -Wa,-I,$(DIR) -Wa,--divide
LDFLAGS = -m$(bits-$(CONFIG_64)) -g -nostdlib -Wl,--build-id=none -static
