
objs-y += entry.o arith.o asm.o calluefi_asm.o int_handler.o string.o
objs-y += callrealmode_asm.o guest_bioshook.o nmi_handler.o process_sysenter.o sx_handler.o
objs-y += thread_switch.o wakeup_entry.o
