
CFLAGS = -nostdinc -g -O \
		 -ffreestanding -fno-builtin -fno-stack-protector $(backtrace) -fno-PIE \
		 -fno-strict-aliasing -Wall -Wno-address-of-packed-member $(CONSTANTS-y) \
		 -I$(DIR) -Iinclude -march=armv8.1-a
ASFLAGS = -g -Wa,-I,$(DIR) -D__ASM__
LDFLAGS = -g -nostdlib -Wl,--build-id=none -static


LDSCRIPT	:= boards/$(shell echo $(CONFIG_AARCH64_BOARD))/bitvisor.lds
